Repository geospoc/v-grid-layout, pull requests merged in 2021-01, with the labels that each got.

#132 fix: add examples in storybook
  src/components/GridItem.vue
  src/components/GridLayout.vue
  src/components/examples/AllowIgnore.stories.js
  src/components/examples/AllowIgnore.vue
  src/components/examples/Basic.stories.js
  src/components/examples/DragFromOutside.stories.js
  src/components/examples/DragFromOutside.vue
  src/components/examples/DynamicAddRemove.stories.js
  src/components/examples/DynamicAddRemove.vue
  src/components/examples/Events.stories.js
  src/components/examples/Events.vue
  src/components/examples/Mirrored.stories.js
  src/components/examples/Mirrored.vue
  src/components/examples/MultipleGrids.stories.js
  src/components/examples/MultipleGrids.vue
  src/components/examples/PreventCollision.stories.js
  src/components/examples/PreventCollision.vue
  src/components/examples/Responsive.stories.js
  src/components/examples/Responsive.vue
  src/components/examples/ResponsivePredefinedLayouts.stories.js
  src/components/examples/ResponsivePredefinedLayouts.vue
Labels: documentation 📙, enhancement 🎉

#152 build(deps): add scss rollup plugin
  build/rollup.config.js
  build/rollup.min.config.js
  package-lock.json
  package.json
Labels: bug 🐛, bugfix 🎾, enhancement 🎉

#153 chore: release v1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug 🐛, bugfix 🎾

#154 fix: call vue-component inside install function
  src/components/index.js
Labels: bugfix 🎾
